CREATE TABLE BRANDS
(
	ID int NOT NULL PRIMARY KEY,
	BRAND_NAME varchar(100) NOT NULL 
);

CREATE TABLE CLOTHES
(
	ID int NOT NULL PRIMARY KEY,
	TYPE varchar(100) NOT NULL 
);

CREATE TABLE BRAND_CLOTHES
(
	BRAND_ID int NOT NULL REFERENCES BRANDS(ID),
	CLOTH_ID int NOT NULL REFERENCES CLOTHES(ID),
	PRICE DECIMAL NOT NULL,
	PRIMARY KEY (BRAND_ID, CLOTH_ID)
);

CREATE TABLE BRAND_CLOTHES_PROPERTIES
(
	BRAND_ID int NOT NULL REFERENCES BRANDS(ID),
	CLOTH_ID int NOT NULL REFERENCES CLOTHES(ID),
	COLOR varchar(300) NOT NULL,
	SIZE varchar(300) NOT NULL,
	PRIMARY KEY (BRAND_ID, CLOTH_ID, COLOR, SIZE)
);